# Generated by Django 3.1.7 on 2021-03-04 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_id', models.CharField(max_length=40)),
                ('quote', models.CharField(max_length=600)),
                ('author', models.CharField(max_length=40)),
            ],
        ),
    ]
