# Generated by Django 3.1.7 on 2021-03-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquotemodel',
            name='permalink',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
