# Generated by Django 3.1.7 on 2021-03-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dailyquotemodel_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquotemodel',
            name='copyright',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
