# Generated by Django 3.1.7 on 2021-03-05 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dailyquotemodel_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBackgroundModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bg_id', models.CharField(max_length=40)),
                ('bg_author', models.CharField(max_length=40)),
                ('bg_url', models.CharField(max_length=80)),
                ('bg_str_b64', models.TextField(max_length=400000)),
            ],
        ),
    ]
