# Generated by Django 3.1.6 on 2021-02-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='slug',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='stack',
            field=models.JSONField(default=list),
        ),
    ]
