# Generated by Django 3.1.7 on 2021-03-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210227_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
